### ISSUE TITLE
Navbar hides FAQ anchors

### ISSUE THREAD

**Issue by saumyasinghal747** [ymath-io/ymath.io#47]
When scrolling through the FAQ, I noticed that the navbar hides the top part of the paragraph.

I think we can fix this through:

```css
body {
    scroll-padding-top: 64px;
}
```
